package chariot.model;

public record AccountPreferences(Prefs prefs, String language)  {
    public record Prefs(
        boolean dark,
        boolean transp,
        String bgImg,
        boolean is3d,
        String theme,
        String pieceSet,
        String theme3d,
        String pieceSet3d,
        String soundSet,
        Integer autoQueen,
        Integer autoThreefold,
        Integer takeback,
        Integer moretime,
        Integer clockTenths,
        boolean clockBar,
        boolean clockSound,
        boolean premove,
        Integer animation,
        Integer pieceNotation,
        boolean captured,
        boolean follow,
        boolean highlight,
        boolean destination,
        Integer coords,
        Integer replay,
        Integer challenge,
        Integer message,
        Integer submitMove,
        Integer confirmResign,
        Integer insightShare,
        Integer keyboardMove,
        boolean voiceMove,
        Integer zen,
        Integer ratings,
        Integer moveEvent,
        Integer rookCastle
        ) {}
}
