name: Build

on:
  push:
    branches:
      - gh-actions
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          path: actions

      - uses: actions/checkout@v4
        with:
          ref: main
          path: chariot

      - name: Download OpenJDK 22
        run: |
          download_url="https://download.java.net/java/GA/jdk22.0.1/c7ec1332f7bb44aeba2eb341ae18aca4/8/GPL/openjdk-22.0.1_linux-x64_bin.tar.gz"
          wget -O $RUNNER_TEMP/java_package.tar.gz $download_url

      - uses: actions/setup-java@v4
        with:
          distribution: 'jdkfile'
          jdkFile: ${{ runner.temp }}/java_package.tar.gz
          java-version: '22'
          architecture: x64

      - name: Check java version
        run: java -Xinternalversion

      - name: Copy pom template
        run: cp actions/pom.template.xml .

      - name: Fetch tags
        run: cd chariot && git fetch --tags

      - name: Run the build.sh script
        run: actions/build.sh

      - name: checksum
        run: sha256sum bundle/*
